config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :buyers, controllers: {
    registrations: 'buyers/registrations'
  }
  devise_for :sellers, controllers: {
    registrations: 'sellers/registrations'
  }
  resources :items do
    member do
      get 'confirmation'
    end
    collection do
      get 'search'
    end
    resources :deals, only:[:show] do
      resources :comments, only:[:create]
    end
    resources :transactions, only:[:index, :create]
  end
  resources :categories, only:[:show]

  devise_scope :seller do
    get 'sellers/:id', to: 'sellers#show', as: 'seller'
    get '/sellers/:id/history', to: 'sellers#history', as: 'history_seller'
    post 'sellers/guest_sign_in', to: 'sellers/sessions#new_guest'
  end

  devise_scope :buyer do
    get 'buyers/:id', to: 'buyers#show', as: 'buyer'
    post 'buyers/guest_sign_in', to: 'buyers/sessions#new_guest'
  end
  
end

app/models/seller.rb
class Seller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :deals

  def self.guest
    find_or_create_by!(email: 'seller_guest@example.com') do |seller|
      seller.password = "guest11"
      seller.nickname = "ゲストユーザー"
      seller.first_name = "ゲスト"
      seller.last_name = "ユーザー"
      seller.first_name_kana = "ゲスト"
      seller.last_name_kana = "ユーザー"
      seller.birth_date = "1950-05-05"
      seller.jender = "男"
      seller.info = "アパレルデザイナー歴10年"
      seller.schedule = "土日終日対応可"
    end
  end

  VALID_NAME_REGIX = /\A[ぁ-んァ-ン一-龥]/
  VALID_KANA_REGIX = /\A[ァ-ヶー－]+\z/
  VALID_PASS_REGIX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password, format: { with: VALID_PASS_REGIX, message: "は文字と数字の両方を含めてください"}
    validates :first_name, format: { with: VALID_NAME_REGIX, message: "は全角で入力してください"}
    validates :last_name, format: { with: VALID_NAME_REGIX, message: "は全角で入力してください"}
    validates :first_name_kana, format: { with: VALID_KANA_REGIX, message: "は全角カタカナで入力してください"}
    validates :last_name_kana, format: { with: VALID_KANA_REGIX, message: "は全角カタカナで入力してください"}
    validates :birth_date
    validates :jender
    validates :info, length: { maximum: 1000 }
    validates :schedule
  end
       
end

app/controllers/sellers/registrations_controller.rb
class Sellers::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only:[:destroy]

  def check_guest
    if resource.email == 'sellers_guest@example.com'
      redirect_to root_path
    end
  end

end

app/controllers/sellers/sessions_controller.rb
class Sellers::SessionsController < Devise::SessionsController
  def new_guest
    seller = Seller.guest
    sign_in seller
    redirect_to root_path
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  
  before_action :set_seller

  
  def show
    @items = @seller.items
  end

  def history
    @deals = @seller.deals.all.order("created_at DESC")

  end

  private

  def set_seller
    @seller = Seller.find(params[:id])
  end

end

app/views/sellers/history.html.erb
<% breadcrumb :seller_history %>

<%= render partial: "items/header" %>

<div class="item-show">
  <div class="seller-header">
    <div class="seller-header-name">
      <%= @seller.nickname %>さんのページ
    </div>
    <div class="seller-header-text">
      購入履歴一覧
    </div>
  </div>

  <div class="seller-item-box">
    <ul class='item-lists'>
      <% @deals.each do |deal| %>
        <li class='seller-list'>
          <p class="seller-item-time">購入日時：<%= deal.created_at.to_s(:datetime_jp) %></p>
          <p class="seller-item-nickname">購入者： <%= deal.buyer.nickname %></p>
          <%= link_to "購入者とチャット", item_deal_path(deal.item_id,deal),class:"seller-item-link" %>
          <div class="seller-item">
            <div class='seller-item-image'>
              <%= image_tag deal.item.image, class: "seller-item-img" %>
            </div>
            <div class="seller-item-right">
              <div class="seller-item-overview">
                <%= deal.item.overview %>
              </div>
              <div class="seller-item-info">
                <%= deal.item.info %>
              </div>
              <div class="seller-item-bottom">
                <div class=seller-item-category>
                  <%= deal.item.category.name %>
                </div>
                <div class="seller-item-price">
                  <div class="seller-item-bottom-price">
                    ¥<%= deal.item.price %>
                  </div>
                  <div class="seller-item-deliveryfee">
                    <%= deal.item.delivery_fee.name %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
      <div class="item-info-wrapper">
        <div class="fotter-link">
          <%= link_to "TOPページへ戻る", root_path, class: "footer-link-content" %>
        </div>
      </div>
</div>

app/views/sellers/show.html.erb
<% breadcrumb :seller_mypage %>

<%= render partial: "items/header" %>

<div class="item-show">
  <div class="seller-header">
      <h1><%= @seller.nickname %>さんのプロフィール</h1>
      <% if @seller == current_seller %>
      <p><%= link_to "#{@seller.nickname}さんのプロフィール修正", edit_seller_registration_path(@seller), class:"seller-header-edit" %></p>
      <% end %>
    <div class="seller-header-content">
      <div class="seller-header-name">
        <h2><%= @seller.nickname %></h2>
      </div>
      <div class="seller-header-right">
        <h3><%= @seller.info %></h3>
        <p><%= @seller.schedule %></p>
      </div>
    </div>
    <div class="seller-header-text">
      出品サービス一覧
    </div>
    <% if @seller == current_seller %>
      <%= link_to "購入された商品の一覧へ", history_seller_path(@seller), class:"history-link" %>
    <%end%>
    
  </div>

  <div class="seller-item-box">
    <ul class='item-lists'>
      <% @items.each do |item| %>
        <li class='seller-list'>
          <%= link_to item_path(item), class:"seller-link" do %>
          <div class="seller-item">
           <div class='seller-item-image'>
              <%= image_tag item.image, class: "seller-item-img" %>
            </div>

            <div class="seller-item-left">
              <div class="seller-item-overview">
                <%= item.overview %>
              </div>
              <div class="seller-item-info">
                <%= item.info %>
              </div>
              <div class="seller-item-bottom">
                <div class=seller-item-category>
                  <%= item.category.name %>
                </div>
                <div class="seller-item-price">
                  <div class="seller-item-bottom-price">
                  ¥<%= item.price %>
                  </div>
                  <div class="seller-item-deliveryfee"></div>
                  <%= item.delivery_fee.name %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
      <div class="item-info-wrapper">
        <div class="fotter-link">
          <%= link_to "TOPページへ戻る", root_path, class: "footer-link-content" %>
        </div>
      </div>


</div>