config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  devise_for :buyers, controllers: {
    registrations: 'buyers/registrations'
  }
  devise_for :sellers, controllers: {
    registrations: 'sellers/registrations'
  }
  resources :items do
    member do
      get 'confirmation'
    end
    collection do
      get 'search'
    end
    resources :deals, only:[:show] do
      resources :comments, only:[:create]
    end
    resources :transactions, only:[:index, :create]
  end
  resources :categories, only:[:show]

  devise_scope :seller do
    get 'sellers/:id', to: 'sellers#show', as: 'seller'
    get '/sellers/:id/history', to: 'sellers#history', as: 'history_seller'
    post 'sellers/guest_sign_in', to: 'sellers/sessions#new_guest'
  end

  devise_scope :buyer do
    get 'buyers/:id', to: 'buyers#show', as: 'buyer'
    post 'buyers/guest_sign_in', to: 'buyers/sessions#new_guest'
  end
  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions


  belongs_to :seller
  has_one_attached :image, dependent: :destroy
  belongs_to_active_hash :category
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :shipping_area
  has_many :deals
  has_many :buyers, through: :deals

  def self.search(search)
    if search != ""
      Item.where('info LIKE(?)', "%#{search}%")
      Item.where('overview LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end

  with_options presence: true do
    validates :image
    validates :overview, length: { maximum: 200}
    validates :info, length: { maximum: 1000 }
    validates :price, numericality: {only_integer: true, greater_than_or_equal_to: 5000, less_than_or_equal_to: 500000}
    validates :category
    validates :delivery_fee
    validates :shipping_area
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :set_item, only:[:show, :edit, :confirmation, :destroy, :update]
  before_action :search_item, only:[:index, :search, :show]

  def index
    @items = Item.all

    @category1 = Category.find(1)
    @category2 = Category.find(2)
    @category3 = Category.find(3)
    @category4 = Category.find(4)
  end

  def new
    if seller_signed_in?
      @item = Item.new
    else
      redirect_to new_seller_registration_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @seller = @item.seller
    @p = @item.price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
  end

  def edit
    if @item.seller.id != current_seller.id
      redirect_to :show
    end

  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      render :edit
    end
  end

  def confirmation
    @seller = @item.seller
    @p = @item.price.to_s.reverse.gsub( /(\d{3})(?=\d)/, '\1,').reverse
  end

  def destroy
    @seller = @item.seller
    if @item.seller.id == current_seller.id
      @item.destroy
      redirect_to seller_path(@seller)
    else
      render :show
    end
  end

  def search
    @results = @i.result.order("created_at DESC")
  end

  private

  def item_params
    params.require(:item).permit(:image, :overview, :info, :category_id, :delivery_fee_id, :shipping_area_id, :price).merge(seller_id: current_seller.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search_item
    @i = Item.ransack(params[:q])
  end

end

app/views/items/_header.html.erb
<%# ページTOP %>
<header>
  <div class="top-page-header">
    <div class="header-left">
      <div class="app-name">
        <a href="/" class= "top-link">
        <h1 class="title">MyPreta</h1>
        </a>
      </div>
    </div>
    <div class="header-right">
    
        <% if seller_signed_in? %>
          <p class="list-tag">出品者用アカウント</p>
            <div class="user_nav grid-6">
              <span><%= link_to current_seller.nickname, edit_seller_registration_path(@current_seller), class: "user-tag" %>
                <ul class="user__info">
                  <li><%= link_to 'ログアウト', destroy_seller_session_path, method: :delete, class: "user-tag" %></li> 
                  <li><%= link_to 'マイページ', seller_path(@current_seller), class: "user-tag" %></li>
                </ul>
              </span>
            </div>
        <% elsif  buyer_signed_in?%>
          <p class="list-tag">購入者用アカウント</p>
            <div class="user_nav grid-6">
              <span><%= link_to current_buyer.nickname, edit_buyer_registration_path(@current_buyer), class: "user-tag" %>
                <ul class="user__info">
                  <li><%= link_to 'ログアウト', destroy_buyer_session_path, method: :delete, class: "user-tag" %></li> 
                  <li><%= link_to 'マイページ', buyer_path(@current_buyer), class: "user-tag" %></li>
                </ul>
              </span>
            </div>
        <% else %>
        <div class="user-list ">
          <div class="user_nav grid-6 nav1">
            <span class="list-tag">出品者用アカウント
              <ul class="user__info">
                <li><%= link_to '出品者としてログイン', new_seller_session_path, class: "user-tag" %></li>
                <li><%= link_to '出品者として新規登録', new_seller_registration_path, class: "user-tag" %></li>
                <li><%= link_to 'ゲストログイン(出品者)', sellers_guest_sign_in_path, method: :post, class: "user-tag" %></li>
              </ul>
            </span>
          </div>
          <div class="user_nav grid-6 nav2">
            <span class="list-tag ">購入者用アカウント
              <ul class="user__info">
                <li><%= link_to '購入者としてログイン', new_buyer_session_path, class: "user-tag" %></li>
                <li><%= link_to '購入者として新規登録', new_buyer_registration_path, class: "user-tag" %></li>
                <li><%= link_to 'ゲストログイン(購入者)', buyers_guest_sign_in_path, method: :post, class: "user-tag" %></li>
              </ul>
            </span>
          </div>
        </div>
        <% end %>
      <%# </ul> %>
    </div>
  </div>
</header>

app/views/items/confirmation.html.erb
<% breadcrumb :item_confirmation %>

<div class="item-confirmation-wrapper">
  <div class="item-confirmation">
    <div class="item-confirmation-content">
      <h1 class="confirmation-text">本当に削除しますか？</h1>
      <p>※削除されたデータは復元できません</p>
      <%= link_to '削除', item_path(@item), method: :delete , class:'item-confirmation-destroy' %>
      </div>
    <div class="confirmation-inner">
      <p>削除する商品情報</p>
      <div class="name">
        <p>＜商品概要＞</p>
        <h4><%= @item.overview %></h4>
      </div>
    </div>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥<%= @p %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>



      <div class="item-info-wrapper">
        <div class="item-info-content">
          <%= @item.info %>
        </div>
        <div class="fotter-link">
        <%= link_to "TOPページへ戻る", root_path, class: "item-link" %>
        </div>
        <div class="footer-link">
        <%= link_to "出品者のページ", seller_path(@seller), class: "footer-link-content" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<% breadcrumb :edit_item %>

<%= render partial: "items/header" %>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>

    <div id="image-list">
    <%= image_tag @item.image, class: "item-current-img", id: "item-current-image" %> 
    </div>


    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        スキルの概要
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :overview, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          スキルの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_fee_id, DeliveryFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id, ShippingArea.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', item_path(@item), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/items/index.html.erb
<% breadcrumb :root %>
<%= render partial: "header" %>
<%# ページTOP %>
<div class='nav'>
  <div class='sub-lists'>
    <div class='lists-left'>
      <%= search_form_for @i, url: search_items_path, local: true, method: :get, class: "search-form" do |f| %>
        <%= f.search_field :info_cont, placeholder: "スキルを検索する", class: "search-input" %>
        <%= f.submit "検索", class: "search-btn" %>
      <% end %>
    </div>
      <%= link_to new_item_path, class:"purchase-btn-text" do %>
        <div class='purchase-btn'>
          <p>出品する</p>
        </div>
      <%end%>
  </div>
</div>
<div class="introduction">
  <h1 class="intro-text">MyPretaではあなただけの服が手に入ります</h1>
</div>
  <div class="category-intro">
    <h2>カテゴリーリスト</h2>
  </div>
<div class="main-menu-lists">
  <div class="main-menu">
    <%= link_to category_path(@category1) do %>
    <div class="lesson-icon">
      <%= image_tag "category1-icon.png", class: "lesson-icon-list" %>
      <p>オーダーメイド</p>
    </div>
    <%end%>
    <p class="txt-contents">自分だけのデザインの服をオーダーできます。<br>世界にひとつだけの個性あふれるデザインを実現することが可能です。</p>
  </div>
  <div class="main-menu">
  <%= link_to category_path(@category2) do %>
    <div class="lesson-icon">
      <%= image_tag "category2-icon.png", class: "lesson-icon-list" %>
      <p>コスプレ</p>
    </div>
  <%end%>
    <p class="txt-contents">自分のサイズにぴったりのコスプレ衣装が手に入ります。<br>細かい箇所までオーダー可能で、自分だけの可愛いが実現できます。</p>
  </div>
  <div class="main-menu">
    <%= link_to category_path(@category3) do %>
    <div class="lesson-icon">
      <%= image_tag "category3-icon.png", class: "lesson-icon-list"%>
      <p>ペット服</p>
    </div>
    <%end%>
    <p class="txt-contents">大切な家族に最高に可愛い洋服をプレゼントできます。<br>帽子・フード付きなど自由自在。</p>
  </div>
  <div class="main-menu">
      <%= link_to category_path(@category4) do %>
    <div class="lesson-icon">
      <%=image_tag "category4-icon.png", class: "lesson-icon-list" %>
      <p>小物</p>
    </div>
    <%end%>
    <p class="txt-contents">普段身に着けるアイテムにこだわりを。<br>周りと差をつけられる素敵なアイテムがオーダー可能です。</p>
  </div>
</div>

<div class="swiper-text">
  人気商品のスライド
</div>
  <!-- Swiper START -->
<div class="swiper-container">
  <!-- メイン表示部分 -->
  <div class="swiper-wrapper">
    <!-- 各スライド -->
    <div class="swiper-slide"><%= image_tag "top1.jpg" %></div>
    <div class="swiper-slide"><%= image_tag "top2.jpg" %></div>
    <div class="swiper-slide"><%= image_tag "top3.jpg" %></div>
    <div class="swiper-slide"><%= image_tag "top4.png" %></div>
  </div>
  <div class="swiper-pagination swiper-pagination-black"></div>
  <div class="swiper-button-prev swiper-button-black"></div>
  <div class="swiper-button-next swiper-button-black"></div>
</div>

    <!-- Swiper END -->



<footer>
  <div class="footer-content">
    <div class="footer-content-left">
      <ul>
        <li><%= link_to "初めてのお客様へ", "#" %></li>
        <li><%= link_to "よくあるご質問", "#" %></li>
        <li><%= link_to "ご利用ガイド", "#" %></li>
      </ul>
      <ul>
        <li><%= link_to "MyPretaのルール", "#" %></li>
        <li><%= link_to "お問い合わせ", "#" %></li>
        <li><%= link_to "退会する", "#" %></li>
      </ul>
    </div>
    <div class="footer-badge">
      <div class="footer-badge-google">
        <%= image_tag "google-play-badge.png", class:"google-badge" %>
      </div>
      <div class="footer-badge-apple">
        <%= image_tag "Download_on_the_App_Store_Badge_JP_blk_100317.png", class:"apple-badge" %>
      </div>
    </div>
  </div>
  <div class="footer-bottom-content">
    <ul>
      <li><%= link_to "利用規約", "#" %></li>
      <li><%= link_to "プライバシーポリシー", "#" %></li>
      <li><%= link_to "特定商取引法による表記", "#" %></li>
    </ul>
  </div>
</footer>

app/views/items/new.html.erb
<% breadcrumb :new_item %>
<%= render partial: "items/header" %>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">スキルの情報を入力</h2>
    <%= form_with model: @item , method: :post, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        スキルサンプル画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>

    <%# 画像プレビュー %>
    <div id="image-list"></div>
    <%#/ 画像プレビュー %>

    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        スキルの概要
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :overview, class:"items-text", id:"item-name", placeholder:"スキルの概要（必須 200文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          スキルの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"スキルの説明（必須 1,000文字まで）例）お好きなデザインのお洋服を作成します。得意なかたちは◯◯です。リボンやフリルが得意です。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: "---"} , {class:"select-box", id:"item-category"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_fee_id, DeliveryFee.all, :id, :name, {include_blank: "---"} , {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送元の地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_area_id, ShippingArea.all, :id, :name, {include_blank: "---"} , {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥5,000~¥500,000)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'TOPページへ戻る', root_path, class:"item-link" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/items/search.html.erb
<% breadcrumb :item_search %>
<%= render partial: "items/header" %>

<div class='item-contents'>
  <h2 class='category-title'>検索結果</h2>
  
  <ul class='item-lists'>
    <% @results.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class="item-overview">
          <%= item.overview %>
        </div>
        <div class='item-info'>
          <div class="item-user-name"><%= item.seller.nickname %></div>
          <div class='item-price'>
            <span><%= item.price %>円<br>(税込み)</span>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to "トップページに戻る", root_path, class:"item-link" %>
</div>

app/views/items/show.html.erb
<% breadcrumb :show_item %>

<%= render partial: "items/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.overview %>
    </h2>
    <p>出品者：<%= @item.seller.nickname %></p>
    <div class='item-img-content'>
      <%= image_tag @item.image ,class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥<%= @p %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>

    <% if seller_signed_in? && (@item.seller_id == current_seller.id) %>
      <%= link_to '商品の編集', edit_item_path(@item), method: :get, class: "item--btn" %>
      <p class='or-text'>or</p>
      <%= link_to '削除', confirmation_item_path(@item) , class:'item--btn' %>
    <% elsif  %>
      <%= link_to '購入画面に進む', item_transactions_path(@item,@transaction) ,class:"item--btn"%>
    <% end %>


      <div class="item-info-wrapper">
          <p>商品の説明</p>
        <div class="item-info-content">
          <%= @item.info %>
        </div>
        <div class="fotter-link">
        <%= link_to "TOPページへ戻る", root_path, class: "footer-link-content" %>
        </div>
        <div class="fotter-link">
        <%= link_to "出品者のページ", seller_path(@seller), class: "footer-link-content" %>
        </div>
      </div>
    </div>
  </div>
</div>